# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CGTA', '0002_auto_20160212_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='sample_image',
            new_name='docfile',
        ),
    ]
