# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 12:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CGTA', '0003_auto_20160212_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='output',
            field=models.ImageField(default=datetime.datetime(2016, 2, 19, 12, 38, 31, 496000, tzinfo=utc), upload_to=b'output/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
