# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CGTA', '0004_document_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='docfile',
            new_name='input',
        ),
    ]
