# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CGTA', '0006_auto_20160220_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='class_type',
            field=models.CharField(default=datetime.datetime(2016, 2, 21, 11, 20, 3, 734000, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
